//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSService8888
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.neusoft.com/", ConfigurationName="WSService8888.IDataStatistics")]
    public interface IDataStatistics
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WSService8888.GetQueueTypesResponse> GetQueueTypesAsync(WSService8888.GetQueueTypes request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WSService8888.GetPatientQueuesResponse> GetPatientQueuesAsync(WSService8888.GetPatientQueues request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WSService8888.GetDatasResponse> GetDatasAsync(WSService8888.GetDatas request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQueueTypes
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQueueTypes", Namespace="http://webservice.neusoft.com/", Order=0)]
        public WSService8888.GetQueueTypesBody Body;
        
        public GetQueueTypes()
        {
        }
        
        public GetQueueTypes(WSService8888.GetQueueTypesBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetQueueTypesBody
    {
        
        public GetQueueTypesBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQueueTypesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQueueTypesResponse", Namespace="http://webservice.neusoft.com/", Order=0)]
        public WSService8888.GetQueueTypesResponseBody Body;
        
        public GetQueueTypesResponse()
        {
        }
        
        public GetQueueTypesResponse(WSService8888.GetQueueTypesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetQueueTypesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public GetQueueTypesResponseBody()
        {
        }
        
        public GetQueueTypesResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPatientQueues
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPatientQueues", Namespace="http://webservice.neusoft.com/", Order=0)]
        public WSService8888.GetPatientQueuesBody Body;
        
        public GetPatientQueues()
        {
        }
        
        public GetPatientQueues(WSService8888.GetPatientQueuesBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetPatientQueuesBody
    {
        
        public GetPatientQueuesBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPatientQueuesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPatientQueuesResponse", Namespace="http://webservice.neusoft.com/", Order=0)]
        public WSService8888.GetPatientQueuesResponseBody Body;
        
        public GetPatientQueuesResponse()
        {
        }
        
        public GetPatientQueuesResponse(WSService8888.GetPatientQueuesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetPatientQueuesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public GetPatientQueuesResponseBody()
        {
        }
        
        public GetPatientQueuesResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDatas
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDatas", Namespace="http://webservice.neusoft.com/", Order=0)]
        public WSService8888.GetDatasBody Body;
        
        public GetDatas()
        {
        }
        
        public GetDatas(WSService8888.GetDatasBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetDatasBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public GetDatasBody()
        {
        }
        
        public GetDatasBody(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDatasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDatasResponse", Namespace="http://webservice.neusoft.com/", Order=0)]
        public WSService8888.GetDatasResponseBody Body;
        
        public GetDatasResponse()
        {
        }
        
        public GetDatasResponse(WSService8888.GetDatasResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetDatasResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public GetDatasResponseBody()
        {
        }
        
        public GetDatasResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IDataStatisticsChannel : WSService8888.IDataStatistics, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class DataStatisticsClient : System.ServiceModel.ClientBase<WSService8888.IDataStatistics>, WSService8888.IDataStatistics
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DataStatisticsClient() : 
                base(DataStatisticsClient.GetDefaultBinding(), DataStatisticsClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DataStatisticsImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataStatisticsClient(EndpointConfiguration endpointConfiguration) : 
                base(DataStatisticsClient.GetBindingForEndpoint(endpointConfiguration), DataStatisticsClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataStatisticsClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DataStatisticsClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataStatisticsClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DataStatisticsClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataStatisticsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSService8888.GetQueueTypesResponse> WSService8888.IDataStatistics.GetQueueTypesAsync(WSService8888.GetQueueTypes request)
        {
            return base.Channel.GetQueueTypesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSService8888.GetQueueTypesResponse> GetQueueTypesAsync()
        {
            WSService8888.GetQueueTypes inValue = new WSService8888.GetQueueTypes();
            inValue.Body = new WSService8888.GetQueueTypesBody();
            return ((WSService8888.IDataStatistics)(this)).GetQueueTypesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSService8888.GetPatientQueuesResponse> WSService8888.IDataStatistics.GetPatientQueuesAsync(WSService8888.GetPatientQueues request)
        {
            return base.Channel.GetPatientQueuesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSService8888.GetPatientQueuesResponse> GetPatientQueuesAsync()
        {
            WSService8888.GetPatientQueues inValue = new WSService8888.GetPatientQueues();
            inValue.Body = new WSService8888.GetPatientQueuesBody();
            return ((WSService8888.IDataStatistics)(this)).GetPatientQueuesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSService8888.GetDatasResponse> WSService8888.IDataStatistics.GetDatasAsync(WSService8888.GetDatas request)
        {
            return base.Channel.GetDatasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSService8888.GetDatasResponse> GetDatasAsync(string arg0)
        {
            WSService8888.GetDatas inValue = new WSService8888.GetDatas();
            inValue.Body = new WSService8888.GetDatasBody();
            inValue.Body.arg0 = arg0;
            return ((WSService8888.IDataStatistics)(this)).GetDatasAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DataStatisticsImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DataStatisticsImplPort))
            {
                return new System.ServiceModel.EndpointAddress("http://10.10.210.31/wsService/ws/data");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DataStatisticsClient.GetBindingForEndpoint(EndpointConfiguration.DataStatisticsImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DataStatisticsClient.GetEndpointAddress(EndpointConfiguration.DataStatisticsImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            DataStatisticsImplPort,
        }
    }
}
